// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App = (function(_super) {
    __extends(App, _super);

    function App() {
      return App.__super__.constructor.apply(this, arguments);
    }

    App.prototype.initialize = function() {
      var dealerHand, deck, playerHand;
      this.set('deck', deck = new Deck());
      this.set('playerHand', deck.dealPlayer());
      this.set('dealerHand', deck.dealDealer());
      deck = this.get('deck');
      playerHand = this.get('playerHand');
      dealerHand = this.get('dealerHand');
      playerHand.on('endTurn', (function(_this) {
        return function() {
          console.log('player turn end');
          return dealerHand.dealerPlay();
        };
      })(this));
      playerHand.on('bust', (function(_this) {
        return function() {
          return console.log('player lost');
        };
      })(this));
      dealerHand.on('bust', (function(_this) {
        return function() {
          return console.log('dealer bust');
        };
      })(this));
      dealerHand.on('endTurn', (function(_this) {
        return function() {
          console.log('dealer turn ended');
          return _this.checkScore();
        };
      })(this));
      return dealerHand.on('blackJack', (function(_this) {
        return function() {
          return console.log('black jack!');
        };
      })(this));
    };

    App.prototype.checkScore = function() {
      var dealerHand, dealerScore, playerHand, playerScore;
      playerHand = this.get('playerHand');
      dealerHand = this.get('dealerHand');
      playerScore = playerHand.scores()[0];
      dealerScore = dealerHand.scores()[0];
      if (playerScore === dealerScore) {
        return console.log('draw');
      } else if (playerScore > dealerScore) {
        return console.log('player wins');
      } else {
        return console.log('dealer wins');
      }
    };

    return App;

  })(Backbone.Model);

}).call(this);

//# sourceMappingURL=App.map
