// Generated by CoffeeScript 1.7.1
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Hand = (function(_super) {
    __extends(Hand, _super);

    function Hand() {
      this.dealerPlay = __bind(this.dealerPlay, this);
      return Hand.__super__.constructor.apply(this, arguments);
    }

    Hand.prototype.model = Card;

    Hand.prototype.initialize = function(array, deck, isDealer) {
      this.deck = deck;
      this.isDealer = isDealer;
    };

    Hand.prototype.hit = function() {
      return this.add(this.deck.pop()).last();
    };

    Hand.prototype.stand = function() {
      return this.trigger('endTurn', this);
    };

    Hand.prototype.scores = function() {
      var hasAce, score;
      hasAce = this.reduce(function(memo, card) {
        return memo || card.get('value') === 1;
      }, false);
      score = this.reduce(function(score, card) {
        return score + (card.get('revealed') ? card.get('value') : 0);
      }, 0);
      if (!this.isDealer) {
        if (score > 21) {
          this.trigger('bust', this);
        }
      }
      if (hasAce) {
        return [score, score + 10];
      } else {
        return [score, score];
      }
    };

    Hand.prototype.dealerPlay = function(index, flag) {
      var _ref;
      console.log(this);
      debugger;
      index = index || 1;
      if (!flag) {
        this.at(0).flip();
      }
      while (this.scores()[index] < 17) {
        this.hit();
      }
      if ((16 < (_ref = this.scores()[index]) && _ref < 21)) {
        this.stand();
      }
      if (this.scores()[index] === 21) {
        this.trigger('blackJack', this);
      }
      if (21 < this.scores()[index]) {
        if (!flag) {
          return this.dealerPlay(0, 'on');
        } else {
          return this.trigger('bust', this);
        }
      }
    };

    return Hand;

  })(Backbone.Collection);

}).call(this);

//# sourceMappingURL=Hand.map
